### ISSUE TITLE
feature: filter function

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/clone-repos#1]
Would be awesome to be able to filter out specific repos. A filter function [already exists](https://github.com/doowb/clone-repos/blob/master/index.js#L68) but it's not exposed. A simple way to add this feature would be something like:

``` js
var filter = function() {
  return true;
};

if (typeof options.filter === 'function') {
  filter = options.filter;
}

var sources = repos.filter(function (repo) {
  return filter(repo) && !repo.fork;
});
```

**Comment by doowb** [comment]
This is a good idea.
Added in 0.1.3.
